name: default
channels:
    - conda-forge
dependencies:
    - python=3.7
    - numpy=1.16.2
    - pandas=0.24.2
    - matplotlib=3.1.0
    - jinja2=2.10.1
    - xarray=0.12.1
    - netcdf4=1.5.0.1
    - pycountry=18.12.8
